from __future__ import annotations

from datetime import datetime
from typing import Any


REPORT_TRANSLATIONS = {
    "English": {
        "title": "CyberCoach Safety Report",
        "date": "Date",
        "scan_type": "Scan Type",
        "risk_level": "Risk Level",
        "confidence": "Confidence",
        "likely_pattern": "Likely Scam Pattern",
        "summary": "Summary",
        "key_findings": "Key Findings",
        "recommended_actions": "Recommended Actions",
        "privacy_mode": "Privacy Mode",
        "generated_by": "Generated by CyberCoach",
        "end": "End of Report",
    },
    "Spanish": {
        "title": "Informe de Seguridad de CyberCoach",
        "date": "Fecha",
        "scan_type": "Tipo de escaneo",
        "risk_level": "Nivel de riesgo",
        "confidence": "Confianza",
        "likely_pattern": "Patron de estafa probable",
        "summary": "Resumen",
        "key_findings": "Hallazgos clave",
        "recommended_actions": "Acciones recomendadas",
        "privacy_mode": "Modo de privacidad",
        "generated_by": "Generado por CyberCoach",
        "end": "Fin del informe",
    },
    "Chinese": {
        "title": "CyberCoach 安全报告",
        "date": "日期",
        "scan_type": "扫描类型",
        "risk_level": "风险级别",
        "confidence": "置信度",
        "likely_pattern": "可能的诈骗模式",
        "summary": "摘要",
        "key_findings": "关键发现",
        "recommended_actions": "建议操作",
        "privacy_mode": "隐私模式",
        "generated_by": "由 CyberCoach 生成",
        "end": "报告结束",
    },
    "Vietnamese": {
        "title": "Bao cao an toan CyberCoach",
        "date": "Ngay",
        "scan_type": "Loai quet",
        "risk_level": "Muc do rui ro",
        "confidence": "Do tin cay",
        "likely_pattern": "Kieu lua dao co kha nang",
        "summary": "Tom tat",
        "key_findings": "Phat hien chinh",
        "recommended_actions": "Hanh dong de xuat",
        "privacy_mode": "Che do rieng tu",
        "generated_by": "Duoc tao boi CyberCoach",
        "end": "Ket thuc bao cao",
    },
    "Korean": {
        "title": "CyberCoach 보안 보고서",
        "date": "날짜",
        "scan_type": "스캔 유형",
        "risk_level": "위험 수준",
        "confidence": "신뢰도",
        "likely_pattern": "가능한 사기 유형",
        "summary": "요약",
        "key_findings": "핵심 발견",
        "recommended_actions": "권장 조치",
        "privacy_mode": "개인정보 보호 모드",
        "generated_by": "CyberCoach 생성",
        "end": "보고서 종료",
    },
    "Tagalog": {
        "title": "Ulat sa Kaligtasan ng CyberCoach",
        "date": "Petsa",
        "scan_type": "Uri ng scan",
        "risk_level": "Antas ng panganib",
        "confidence": "Kumpiyansa",
        "likely_pattern": "Posibleng uri ng scam",
        "summary": "Buod",
        "key_findings": "Mahahalagang nakita",
        "recommended_actions": "Mga inirerekomendang aksyon",
        "privacy_mode": "Privacy mode",
        "generated_by": "Ginawa ng CyberCoach",
        "end": "Katapusan ng ulat",
    },
    "French": {
        "title": "Rapport de securite CyberCoach",
        "date": "Date",
        "scan_type": "Type d'analyse",
        "risk_level": "Niveau de risque",
        "confidence": "Confiance",
        "likely_pattern": "Type d'arnaque probable",
        "summary": "Resume",
        "key_findings": "Points cles",
        "recommended_actions": "Actions recommandees",
        "privacy_mode": "Mode confidentialite",
        "generated_by": "Genere par CyberCoach",
        "end": "Fin du rapport",
    },
}


def _as_dict(result: Any) -> dict[str, Any]:
    if hasattr(result, "model_dump"):
        return result.model_dump()
    return dict(result)


def _report_language(payload: dict[str, Any]) -> str:
    language = payload.get("metadata", {}).get("language", "English")
    return language if language in REPORT_TRANSLATIONS else "English"


def generate_text_report(result: Any) -> str:
    """Generate a plain-text report from the unified scan response."""
    payload = _as_dict(result)
    translations = REPORT_TRANSLATIONS[_report_language(payload)]
    lines = [
        f"=== {translations['title']} ===",
        f"{translations['date']}: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"{translations['scan_type']}: {payload['scan_type'].upper()}",
        f"{translations['risk_level']}: {payload['risk_label'].upper()}",
        f"{translations['confidence']}: {payload['confidence']}",
        f"{translations['likely_pattern']}: {payload['likely_scam_pattern']}",
        f"\n{translations['summary']}: {payload['summary']}",
        f"\n{translations['key_findings']}:",
    ]
    for index, reason in enumerate(payload["top_reasons"], start=1):
        lines.append(f"  {index}. {reason}")
    lines.append(f"\n{translations['recommended_actions']}:")
    for index, action in enumerate(payload["recommended_actions"], start=1):
        lines.append(f"  {index}. {action}")
    if payload.get("redacted_input"):
        redaction_count = payload.get("metadata", {}).get("redaction_count", 0)
        lines.append(f"\n[{translations['privacy_mode']}: {redaction_count} item(s) redacted before analysis]")
    lines.append(f"\n=== {translations['end']} ===")
    return "\n".join(lines)


def generate_markdown_report(result: Any) -> str:
    """Generate a markdown report from the unified scan response."""
    payload = _as_dict(result)
    translations = REPORT_TRANSLATIONS[_report_language(payload)]
    lines = [
        f"# {translations['title']}",
        f"**{translations['date']}:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**{translations['scan_type']}:** {payload['scan_type'].title()}",
        f"**{translations['risk_level']}:** {payload['risk_label']}",
        f"**{translations['confidence']}:** {payload['confidence']}",
        f"**{translations['likely_pattern']}:** {payload['likely_scam_pattern']}",
        f"\n## {translations['summary']}\n{payload['summary']}",
        f"\n## {translations['key_findings']}",
    ]
    for index, reason in enumerate(payload["top_reasons"], start=1):
        lines.append(f"{index}. {reason}")
    lines.append(f"\n## {translations['recommended_actions']}")
    for action in payload["recommended_actions"]:
        lines.append(f"- [ ] {action}")
    if payload.get("redacted_input"):
        redaction_count = payload.get("metadata", {}).get("redaction_count", 0)
        lines.append(f"\n> {translations['privacy_mode']}: {redaction_count} item(s) redacted before analysis")
    lines.append(f"\n---\n{translations['generated_by']}")
    return "\n".join(lines)
