from __future__ import annotations

from datetime import datetime
from typing import Any

from .service_data import report_translations

REPORT_TRANSLATIONS = report_translations()
DEFAULT_REPORT_TRANSLATION = {
    "title": "CyberCoach Safety Report",
    "date": "Date",
    "scan_type": "Scan Type",
    "risk_level": "Risk Level",
    "confidence": "Confidence",
    "likely_pattern": "Likely Scam Pattern",
    "summary": "Summary",
    "key_findings": "Key Findings",
    "recommended_actions": "Recommended Actions",
    "privacy_mode": "Privacy Mode",
    "generated_by": "Generated by CyberCoach",
    "end": "End of Report",
}


def _as_dict(result: Any) -> dict[str, Any]:
    if hasattr(result, "model_dump"):
        return result.model_dump()
    return dict(result)


def _report_language(payload: dict[str, Any]) -> str:
    language = payload.get("metadata", {}).get("language", "English")
    if language in REPORT_TRANSLATIONS:
        return language
    if "English" in REPORT_TRANSLATIONS:
        return "English"
    return next(iter(REPORT_TRANSLATIONS), "English")


def _translations_for(payload: dict[str, Any]) -> dict[str, str]:
    return REPORT_TRANSLATIONS.get(_report_language(payload), DEFAULT_REPORT_TRANSLATION)


def generate_text_report(result: Any) -> str:
    """Generate a plain-text report from the unified scan response."""
    payload = _as_dict(result)
    translations = _translations_for(payload)
    lines = [
        f"=== {translations['title']} ===",
        f"{translations['date']}: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"{translations['scan_type']}: {payload['scan_type'].upper()}",
        f"{translations['risk_level']}: {payload['risk_label'].upper()}",
        f"{translations['confidence']}: {payload['confidence']}",
        f"{translations['likely_pattern']}: {payload['likely_scam_pattern']}",
        f"\n{translations['summary']}: {payload['summary']}",
        f"\n{translations['key_findings']}:",
    ]
    for index, reason in enumerate(payload["top_reasons"], start=1):
        lines.append(f"  {index}. {reason}")
    lines.append(f"\n{translations['recommended_actions']}:")
    for index, action in enumerate(payload["recommended_actions"], start=1):
        lines.append(f"  {index}. {action}")

    metadata = payload.get("metadata", {})
    consensus = metadata.get("consensus") or {}
    model_runs = metadata.get("model_runs") or []
    heuristic_findings = metadata.get("heuristic_findings") or []
    url_evidence = metadata.get("url_evidence") or []
    evidence_buckets = metadata.get("evidence_buckets") or []
    url_live_inspection = metadata.get("url_live_inspection") or []
    ocr_metadata = metadata.get("ocr") or {}

    if metadata.get("decision_source"):
        lines.append(f"\nDecision Source: {metadata['decision_source']}")
    if consensus.get("summary"):
        lines.append(f"Consensus: {consensus['summary']}")
    if model_runs:
        lines.append("\nModel Assessments:")
        for index, item in enumerate(model_runs, start=1):
            confidence = item.get("confidence")
            confidence_label = f" ({round(confidence * 100)}%)" if isinstance(confidence, (int, float)) else ""
            lines.append(f"  {index}. {item.get('model', 'model')} -> {item.get('risk_level', 'unknown')}{confidence_label}")
            explanation = str(item.get("explanation") or "").strip()
            if explanation:
                lines.append(f"     {explanation}")
    if heuristic_findings:
        lines.append("\nTechnical Details:")
        for index, item in enumerate(heuristic_findings, start=1):
            lines.append(f"  {index}. [{item.get('severity', 'medium')}] {item.get('type', 'signal')}: {item.get('detail', '')}")
    if evidence_buckets:
        lines.append("\nEvidence Buckets:")
        for item in evidence_buckets:
            lines.append(
                f"  - {item.get('key', 'bucket')}: score {item.get('score', 0)} | findings {item.get('finding_count', 0)}"
            )
            if item.get("summary"):
                lines.append(f"    {item.get('summary')}")
    if url_evidence:
        lines.append("\nURL Evidence:")
        for index, item in enumerate(url_evidence, start=1):
            lines.append(
                f"  {index}. {item.get('domain', '')} -> registered domain {item.get('registrable_domain', '')} | tld {item.get('tld', '')}"
            )
    if url_live_inspection:
        lines.append("\nDestination Inspection:")
        for index, item in enumerate(url_live_inspection, start=1):
            lines.append(f"  {index}. {item.get('normalized_url', '')}")
            if item.get("blocked_reason"):
                lines.append(f"     blocked: {item.get('blocked_reason')}")
                continue
            if item.get("error") and not item.get("inspection_succeeded"):
                lines.append(f"     error: {item.get('error')}")
                continue
            lines.append(f"     final: {item.get('final_url') or item.get('normalized_url')}")
            lines.append(f"     redirects: {len(item.get('redirect_chain') or [])}")
            if item.get("status_code") is not None:
                lines.append(f"     status: {item.get('status_code')}")
            if item.get("page_title"):
                lines.append(f"     title: {item.get('page_title')}")
    if ocr_metadata:
        lines.append("\nScreenshot OCR:")
        if ocr_metadata.get("ocr_confidence") is not None:
            lines.append(f"  confidence: {round(float(ocr_metadata['ocr_confidence']) * 100)}%")
        if ocr_metadata.get("layout_summary"):
            lines.append(f"  layout: {ocr_metadata.get('layout_summary')}")
        if ocr_metadata.get("ocr_override_used"):
            lines.append("  manual override: yes")
        warnings = ocr_metadata.get("ocr_warnings") or []
        if warnings:
            lines.append("  warnings:")
            for item in warnings:
                lines.append(f"    - {item}")
        visual_signals = ocr_metadata.get("visual_signals") or []
        if visual_signals:
            lines.append("  visual signals:")
            for item in visual_signals:
                lines.append(
                    f"    - [{item.get('severity', 'medium')}] {item.get('type', 'signal')}: {item.get('detail', '')}"
                )
        qr_payloads = ocr_metadata.get("qr_payloads") or []
        if qr_payloads:
            lines.append("  detected QR codes:")
            for index, item in enumerate(qr_payloads, start=1):
                lines.append(f"    {index}. {item}")
    if payload.get("redacted_input"):
        redaction_count = payload.get("metadata", {}).get("redaction_count", 0)
        lines.append(f"\n[{translations['privacy_mode']}: {redaction_count} item(s) redacted before analysis]")
    lines.append(f"\n=== {translations['end']} ===")
    return "\n".join(lines)


def generate_markdown_report(result: Any) -> str:
    """Generate a markdown report from the unified scan response."""
    payload = _as_dict(result)
    translations = _translations_for(payload)
    lines = [
        f"# {translations['title']}",
        f"**{translations['date']}:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**{translations['scan_type']}:** {payload['scan_type'].title()}",
        f"**{translations['risk_level']}:** {payload['risk_label']}",
        f"**{translations['confidence']}:** {payload['confidence']}",
        f"**{translations['likely_pattern']}:** {payload['likely_scam_pattern']}",
        f"\n## {translations['summary']}\n{payload['summary']}",
        f"\n## {translations['key_findings']}",
    ]
    for index, reason in enumerate(payload["top_reasons"], start=1):
        lines.append(f"{index}. {reason}")
    lines.append(f"\n## {translations['recommended_actions']}")
    for action in payload["recommended_actions"]:
        lines.append(f"- [ ] {action}")

    metadata = payload.get("metadata", {})
    consensus = metadata.get("consensus") or {}
    model_runs = metadata.get("model_runs") or []
    heuristic_findings = metadata.get("heuristic_findings") or []
    url_evidence = metadata.get("url_evidence") or []
    evidence_buckets = metadata.get("evidence_buckets") or []
    url_live_inspection = metadata.get("url_live_inspection") or []
    ocr_metadata = metadata.get("ocr") or {}

    if metadata.get("decision_source"):
        lines.append(f"\n**Decision Source:** {metadata['decision_source']}")
    if consensus.get("summary"):
        lines.append(f"\n**Consensus:** {consensus['summary']}")
    if model_runs:
        lines.append("\n## Model Assessments")
        for item in model_runs:
            confidence = item.get("confidence")
            confidence_label = f" ({round(confidence * 100)}%)" if isinstance(confidence, (int, float)) else ""
            lines.append(f"- **{item.get('model', 'model')}**: {item.get('risk_level', 'unknown')}{confidence_label}")
            explanation = str(item.get("explanation") or "").strip()
            if explanation:
                lines.append(f"  - {explanation}")
    if heuristic_findings:
        lines.append("\n## Technical Details")
        for item in heuristic_findings:
            lines.append(f"- **{item.get('type', 'signal')}** ({item.get('severity', 'medium')}): {item.get('detail', '')}")
    if evidence_buckets:
        lines.append("\n## Evidence Buckets")
        for item in evidence_buckets:
            lines.append(f"- **{item.get('key', 'bucket')}**: score {item.get('score', 0)} with {item.get('finding_count', 0)} finding(s)")
            if item.get("summary"):
                lines.append(f"  - {item.get('summary')}")
    if url_evidence:
        lines.append("\n## URL Evidence")
        for item in url_evidence:
            lines.append(
                f"- **{item.get('domain', '')}** -> registered domain `{item.get('registrable_domain', '')}` with TLD `{item.get('tld', '')}`"
            )
    if url_live_inspection:
        lines.append("\n## Destination Inspection")
        for item in url_live_inspection:
            lines.append(f"- **{item.get('normalized_url', '')}**")
            if item.get("blocked_reason"):
                lines.append(f"  - blocked: {item.get('blocked_reason')}")
                continue
            if item.get("error") and not item.get("inspection_succeeded"):
                lines.append(f"  - error: {item.get('error')}")
                continue
            lines.append(f"  - final: `{item.get('final_url') or item.get('normalized_url')}`")
            lines.append(f"  - redirects: {len(item.get('redirect_chain') or [])}")
            if item.get("status_code") is not None:
                lines.append(f"  - status: {item.get('status_code')}")
            if item.get("page_title"):
                lines.append(f"  - title: {item.get('page_title')}")
    if ocr_metadata:
        lines.append("\n## Screenshot OCR")
        if ocr_metadata.get("ocr_confidence") is not None:
            lines.append(f"- confidence: {round(float(ocr_metadata['ocr_confidence']) * 100)}%")
        if ocr_metadata.get("layout_summary"):
            lines.append(f"- layout: {ocr_metadata.get('layout_summary')}")
        if ocr_metadata.get("ocr_override_used"):
            lines.append("- manual override: yes")
        warnings = ocr_metadata.get("ocr_warnings") or []
        if warnings:
            lines.append("- warnings:")
            for item in warnings:
                lines.append(f"  - {item}")
        visual_signals = ocr_metadata.get("visual_signals") or []
        if visual_signals:
            lines.append("- visual signals:")
            for item in visual_signals:
                lines.append(
                    f"  - **{item.get('type', 'signal')}** ({item.get('severity', 'medium')}): {item.get('detail', '')}"
                )
        qr_payloads = ocr_metadata.get("qr_payloads") or []
        if qr_payloads:
            lines.append("\n## Detected QR Codes")
            for item in qr_payloads:
                lines.append(f"- `{item}`")
    if payload.get("redacted_input"):
        redaction_count = payload.get("metadata", {}).get("redaction_count", 0)
        lines.append(f"\n> {translations['privacy_mode']}: {redaction_count} item(s) redacted before analysis")
    lines.append(f"\n---\n{translations['generated_by']}")
    return "\n".join(lines)
