from __future__ import annotations

from copy import deepcopy
from datetime import datetime
import re
from typing import Any

from .pii import redact_pii
from .service_data import report_translations

REPORT_TRANSLATIONS = report_translations()
DEFAULT_REPORT_TRANSLATION = {
    "title": "CyberCoach Safety Report",
    "date": "Date",
    "scan_type": "Scan Type",
    "risk_level": "Risk Level",
    "confidence": "Confidence",
    "likely_pattern": "Likely Scam Pattern",
    "summary": "Summary",
    "key_findings": "Key Findings",
    "recommended_actions": "Recommended Actions",
    "privacy_mode": "Privacy Mode",
    "generated_by": "Generated by CyberCoach",
    "end": "End of Report",
}

_CONTROL_CHAR_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")
_MARKDOWN_ESCAPE_TABLE = str.maketrans(
    {
        "\\": "\\\\",
        "`": "\\`",
        "*": "\\*",
        "_": "\\_",
        "{": "\\{",
        "}": "\\}",
        "[": "\\[",
        "]": "\\]",
        "(": "\\(",
        ")": "\\)",
        "#": "\\#",
        "+": "\\+",
        "-": "\\-",
        "!": "\\!",
        "|": "\\|",
        ">": "\\>",
        "<": "\\<",
    }
)


def _as_dict(result: Any) -> dict[str, Any]:
    if hasattr(result, "model_dump"):
        return result.model_dump()
    return dict(result)


def _report_language(payload: dict[str, Any]) -> str:
    language = payload.get("metadata", {}).get("language", "English")
    if language in REPORT_TRANSLATIONS:
        return language
    if "English" in REPORT_TRANSLATIONS:
        return "English"
    return next(iter(REPORT_TRANSLATIONS), "English")


def _translations_for(payload: dict[str, Any]) -> dict[str, str]:
    return REPORT_TRANSLATIONS.get(_report_language(payload), DEFAULT_REPORT_TRANSLATION)


def _protect_text(value: Any) -> Any:
    if value is None:
        return None
    protected, _ = redact_pii(str(value))
    return protected


def _normalize_report_text(value: Any, *, multiline: bool = False) -> str:
    if value is None:
        return ""

    normalized = str(value).replace("\r\n", "\n").replace("\r", "\n")
    normalized = _CONTROL_CHAR_RE.sub("", normalized)
    if multiline:
        return "\n".join(line.rstrip() for line in normalized.split("\n")).strip()
    return " ".join(part for part in normalized.split("\n") if part).strip()


def _markdown_text(value: Any, *, multiline: bool = False) -> str:
    normalized = _normalize_report_text(value, multiline=multiline)
    if not normalized:
        return ""
    if multiline:
        return "\n".join(line.translate(_MARKDOWN_ESCAPE_TABLE) for line in normalized.split("\n"))
    return normalized.translate(_MARKDOWN_ESCAPE_TABLE)


def _text_report_value(value: Any, *, multiline: bool = False) -> str:
    return _normalize_report_text(value, multiline=multiline)


def _sanitize_payload_for_report(payload: dict[str, Any]) -> dict[str, Any]:
    metadata = payload.get("metadata", {})
    if not metadata.get("privacy_mode"):
        return payload

    sanitized = deepcopy(payload)
    if sanitized.get("original_input") is not None:
        sanitized["original_input"] = _protect_text(sanitized.get("redacted_input") or sanitized.get("original_input"))

    ocr_metadata = sanitized.get("metadata", {}).get("ocr") or {}
    for key in ("extracted_text", "analysis_text", "original_extracted_text", "ocr_override_text"):
        if key in ocr_metadata:
            ocr_metadata[key] = _protect_text(ocr_metadata.get(key))
    if isinstance(ocr_metadata.get("qr_payloads"), list):
        ocr_metadata["qr_payloads"] = [_protect_text(item) for item in ocr_metadata["qr_payloads"]]

    document_metadata = sanitized.get("metadata", {}).get("document") or {}
    for key in ("text_preview", "extracted_text", "ocr_text"):
        if key in document_metadata:
            document_metadata[key] = _protect_text(document_metadata.get(key))
    if isinstance(document_metadata.get("extracted_urls"), list):
        document_metadata["extracted_urls"] = [_protect_text(item) for item in document_metadata["extracted_urls"]]
    if isinstance(document_metadata.get("qr_payloads"), list):
        document_metadata["qr_payloads"] = [_protect_text(item) for item in document_metadata["qr_payloads"]]
    if isinstance(document_metadata.get("link_pairs"), list):
        for item in document_metadata["link_pairs"]:
            if isinstance(item, dict):
                if "display_text" in item:
                    item["display_text"] = _protect_text(item.get("display_text"))
                if "target_url" in item:
                    item["target_url"] = _protect_text(item.get("target_url"))

    voice_metadata = sanitized.get("metadata", {}).get("voice") or {}
    if "transcript_text" in voice_metadata:
        voice_metadata["transcript_text"] = _protect_text(voice_metadata.get("transcript_text"))
    if isinstance(voice_metadata.get("transcript_segments"), list):
        for item in voice_metadata["transcript_segments"]:
            if isinstance(item, dict) and "text" in item:
                item["text"] = _protect_text(item.get("text"))

    if isinstance(sanitized.get("metadata", {}).get("url_live_inspection"), list):
        for item in sanitized["metadata"]["url_live_inspection"]:
            if not isinstance(item, dict):
                continue
            for key in ("normalized_url", "final_url", "meta_refresh_target", "page_excerpt"):
                if key in item:
                    item[key] = _protect_text(item.get(key))
            if isinstance(item.get("redirect_chain"), list):
                for redirect in item["redirect_chain"]:
                    if isinstance(redirect, dict):
                        if "from_url" in redirect:
                            redirect["from_url"] = _protect_text(redirect.get("from_url"))
                        if "to_url" in redirect:
                            redirect["to_url"] = _protect_text(redirect.get("to_url"))

    return sanitized


def generate_text_report(result: Any) -> str:
    """Generate a plain-text report from the unified scan response."""
    payload = _sanitize_payload_for_report(_as_dict(result))
    translations = _translations_for(payload)
    lines = [
        f"=== {translations['title']} ===",
        f"{translations['date']}: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"{translations['scan_type']}: {_text_report_value(payload['scan_type']).upper()}",
        f"{translations['risk_level']}: {_text_report_value(payload['risk_label']).upper()}",
        f"{translations['confidence']}: {_text_report_value(payload['confidence'])}",
        f"{translations['likely_pattern']}: {_text_report_value(payload['likely_scam_pattern'])}",
        f"\n{translations['summary']}: {_text_report_value(payload['summary'], multiline=True)}",
        f"\n{translations['key_findings']}:",
    ]
    for index, reason in enumerate(payload["top_reasons"], start=1):
        lines.append(f"  {index}. {_text_report_value(reason)}")
    lines.append(f"\n{translations['recommended_actions']}:")
    for index, action in enumerate(payload["recommended_actions"], start=1):
        lines.append(f"  {index}. {_text_report_value(action)}")

    metadata = payload.get("metadata", {})
    consensus = metadata.get("consensus") or {}
    model_runs = metadata.get("model_runs") or []
    heuristic_findings = metadata.get("heuristic_findings") or []
    url_evidence = metadata.get("url_evidence") or []
    evidence_buckets = metadata.get("evidence_buckets") or []
    url_live_inspection = metadata.get("url_live_inspection") or []
    ocr_metadata = metadata.get("ocr") or {}
    document_metadata = metadata.get("document") or {}
    voice_metadata = metadata.get("voice") or {}

    if metadata.get("decision_source"):
        lines.append(f"\nReview Source: {_text_report_value(metadata['decision_source'])}")
    if consensus.get("summary"):
        lines.append(f"AI Review Summary: {_text_report_value(consensus['summary'], multiline=True)}")
    if model_runs:
        lines.append("\nModel Reviews:")
        for index, item in enumerate(model_runs, start=1):
            confidence = item.get("confidence")
            confidence_label = f" ({round(confidence * 100)}%)" if isinstance(confidence, (int, float)) else ""
            lines.append(
                f"  {index}. {_text_report_value(item.get('model', 'model'))} -> {_text_report_value(item.get('risk_level', 'unknown'))}{confidence_label}"
            )
            explanation = str(item.get("explanation") or "").strip()
            if explanation:
                lines.append(f"     {_text_report_value(explanation, multiline=True)}")
    if heuristic_findings:
        lines.append("\nTechnical Reasons:")
        for index, item in enumerate(heuristic_findings, start=1):
            lines.append(
                f"  {index}. [{_text_report_value(item.get('severity', 'medium'))}] {_text_report_value(item.get('type', 'signal'))}: {_text_report_value(item.get('detail', ''))}"
            )
    if evidence_buckets:
        lines.append("\nWhere The Risk Comes From:")
        for item in evidence_buckets:
            lines.append(
                f"  - {_text_report_value(item.get('key', 'bucket'))}: score {item.get('score', 0)} | findings {item.get('finding_count', 0)}"
            )
            if item.get("summary"):
                lines.append(f"    {_text_report_value(item.get('summary'), multiline=True)}")
    if url_evidence:
        lines.append("\nLink Details:")
        for index, item in enumerate(url_evidence, start=1):
            lines.append(
                f"  {index}. {_text_report_value(item.get('domain', ''))} -> registered domain {_text_report_value(item.get('registrable_domain', ''))} | tld {_text_report_value(item.get('tld', ''))}"
            )
    if url_live_inspection:
        lines.append("\nDestination Check:")
        for index, item in enumerate(url_live_inspection, start=1):
            lines.append(f"  {index}. {_text_report_value(item.get('normalized_url', ''))}")
            if item.get("blocked_reason"):
                lines.append(f"     blocked: {_text_report_value(item.get('blocked_reason'))}")
                continue
            if item.get("error") and not item.get("inspection_succeeded"):
                lines.append(f"     error: {_text_report_value(item.get('error'))}")
                continue
            lines.append(f"     final: {_text_report_value(item.get('final_url') or item.get('normalized_url'))}")
            lines.append(f"     redirects: {len(item.get('redirect_chain') or [])}")
            if item.get("status_code") is not None:
                lines.append(f"     status: {item.get('status_code')}")
            if item.get("page_title"):
                lines.append(f"     title: {_text_report_value(item.get('page_title'))}")
    if ocr_metadata:
        lines.append("\nScreenshot OCR:")
        if ocr_metadata.get("ocr_confidence") is not None:
            lines.append(f"  confidence: {round(float(ocr_metadata['ocr_confidence']) * 100)}%")
        if ocr_metadata.get("layout_summary"):
            lines.append(f"  layout: {_text_report_value(ocr_metadata.get('layout_summary'), multiline=True)}")
        if ocr_metadata.get("ocr_override_used"):
            lines.append("  manual override: yes")
        warnings = ocr_metadata.get("ocr_warnings") or []
        if warnings:
            lines.append("  warnings:")
            for item in warnings:
                lines.append(f"    - {_text_report_value(item)}")
        visual_signals = ocr_metadata.get("visual_signals") or []
        if visual_signals:
            lines.append("  visual signals:")
            for item in visual_signals:
                lines.append(
                    f"    - [{_text_report_value(item.get('severity', 'medium'))}] {_text_report_value(item.get('type', 'signal'))}: {_text_report_value(item.get('detail', ''))}"
                )
        qr_payloads = ocr_metadata.get("qr_payloads") or []
        if qr_payloads:
            lines.append("  detected QR codes:")
            for index, item in enumerate(qr_payloads, start=1):
                lines.append(f"    {index}. {_text_report_value(item)}")
    if document_metadata:
        lines.append("\nDocument X-Ray:")
        lines.append(f"  file: {_text_report_value(document_metadata.get('file_name', 'uploaded-document'))}")
        lines.append(f"  type: {_text_report_value(document_metadata.get('file_type', 'document')).upper()}")
        file_size = document_metadata.get("file_size")
        if isinstance(file_size, int):
            lines.append(f"  size: {file_size} bytes")
        if document_metadata.get("parser"):
            lines.append(f"  parser: {_text_report_value(document_metadata.get('parser'))}")
        lines.append(f"  inspectable: {'yes' if document_metadata.get('inspectable', True) else 'limited'}")
        if document_metadata.get("protected"):
            lines.append("  protected or encrypted: yes")
        if document_metadata.get("macro_enabled"):
            lines.append("  macro-enabled: yes")
        if document_metadata.get("image_based"):
            lines.append("  image-based: yes")
        if document_metadata.get("ocr_fallback_used"):
            line = f"  OCR fallback: yes ({document_metadata.get('ocr_pages_analyzed', 0)} page(s) checked"
            if document_metadata.get("ocr_page_limit"):
                line += f", limit {document_metadata.get('ocr_page_limit')}"
            line += ")"
            lines.append(line)
        if document_metadata.get("page_count") is not None:
            lines.append(f"  pages: {document_metadata.get('page_count')}")
        if document_metadata.get("section_count") is not None:
            lines.append(f"  sections: {document_metadata.get('section_count')}")
        if document_metadata.get("image_count") is not None:
            lines.append(f"  embedded images: {document_metadata.get('image_count')}")
        if document_metadata.get("text_preview"):
            lines.append(f"  preview: {_text_report_value(document_metadata.get('text_preview'), multiline=True)}")
        limitations = document_metadata.get("limitations") or []
        if limitations:
            lines.append("  limitations:")
            for item in limitations:
                lines.append(f"    - {_text_report_value(item)}")
        link_pairs = document_metadata.get("link_pairs") or []
        if link_pairs:
            lines.append("  embedded links:")
            for index, item in enumerate(link_pairs, start=1):
                display_text = item.get("display_text") or f"link {index}"
                target_url = item.get("target_url") or "unknown destination"
                lines.append(f"    {index}. {_text_report_value(display_text)} -> {_text_report_value(target_url)}")
        qr_payloads = document_metadata.get("qr_payloads") or []
        if qr_payloads:
            lines.append("  detected document QR codes:")
            for index, item in enumerate(qr_payloads, start=1):
                lines.append(f"    {index}. {_text_report_value(item)}")
    if voice_metadata:
        lines.append("\nCall Guard:")
        lines.append(f"  session id: {_text_report_value(voice_metadata.get('session_id', 'voice-session'))}")
        if voice_metadata.get("analysis_state"):
            lines.append(f"  state: {_text_report_value(voice_metadata.get('analysis_state'))}")
        if voice_metadata.get("elapsed_seconds") is not None:
            lines.append(f"  elapsed: {voice_metadata.get('elapsed_seconds')}s")
        if voice_metadata.get("transcript_word_count") is not None:
            lines.append(f"  transcript words: {voice_metadata.get('transcript_word_count')}")
        warnings = voice_metadata.get("live_warnings") or []
        if warnings:
            lines.append("  live warnings:")
            for item in warnings:
                lines.append(f"    - {_text_report_value(item)}")
        questions = voice_metadata.get("challenge_questions") or []
        if questions:
            lines.append("  challenge questions:")
            for index, item in enumerate(questions, start=1):
                lines.append(f"    {index}. {_text_report_value(item)}")
        voice_signals = voice_metadata.get("voice_signals") or []
        if voice_signals:
            lines.append("  voice-pattern signals:")
            for item in voice_signals:
                lines.append(
                    f"    - [{_text_report_value(item.get('severity', 'low'))}] {_text_report_value(item.get('type', 'voice_signal'))}: {_text_report_value(item.get('detail', ''))}"
                )
        segments = voice_metadata.get("transcript_segments") or []
        if segments:
            lines.append("  transcript segments:")
            for index, item in enumerate(segments[-8:], start=1):
                lines.append(f"    {index}. {_text_report_value(item.get('text', ''))}")
    if payload.get("redacted_input"):
        redaction_count = payload.get("metadata", {}).get("redaction_count", 0)
        lines.append(f"\n[{translations['privacy_mode']}: {redaction_count} item(s) redacted before analysis]")
    lines.append(f"\n=== {translations['end']} ===")
    return "\n".join(lines)


def generate_markdown_report(result: Any) -> str:
    """Generate a markdown report from the unified scan response."""
    payload = _sanitize_payload_for_report(_as_dict(result))
    translations = _translations_for(payload)
    lines = [
        f"# {translations['title']}",
        f"**{translations['date']}:** {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"**{translations['scan_type']}:** {_markdown_text(payload['scan_type']).title()}",
        f"**{translations['risk_level']}:** {_markdown_text(payload['risk_label'])}",
        f"**{translations['confidence']}:** {_markdown_text(payload['confidence'])}",
        f"**{translations['likely_pattern']}:** {_markdown_text(payload['likely_scam_pattern'])}",
        f"\n## {translations['summary']}\n{_markdown_text(payload['summary'], multiline=True)}",
        f"\n## {translations['key_findings']}",
    ]
    for index, reason in enumerate(payload["top_reasons"], start=1):
        lines.append(f"{index}. {_markdown_text(reason)}")
    lines.append(f"\n## {translations['recommended_actions']}")
    for action in payload["recommended_actions"]:
        lines.append(f"- [ ] {_markdown_text(action)}")

    metadata = payload.get("metadata", {})
    consensus = metadata.get("consensus") or {}
    model_runs = metadata.get("model_runs") or []
    heuristic_findings = metadata.get("heuristic_findings") or []
    url_evidence = metadata.get("url_evidence") or []
    evidence_buckets = metadata.get("evidence_buckets") or []
    url_live_inspection = metadata.get("url_live_inspection") or []
    ocr_metadata = metadata.get("ocr") or {}
    document_metadata = metadata.get("document") or {}
    voice_metadata = metadata.get("voice") or {}

    if metadata.get("decision_source"):
        lines.append(f"\n**Review Source:** {_markdown_text(metadata['decision_source'])}")
    if consensus.get("summary"):
        lines.append(f"\n**AI Review Summary:** {_markdown_text(consensus['summary'], multiline=True)}")
    if model_runs:
        lines.append("\n## Model Reviews")
        for item in model_runs:
            confidence = item.get("confidence")
            confidence_label = f" ({round(confidence * 100)}%)" if isinstance(confidence, (int, float)) else ""
            lines.append(
                f"- **{_markdown_text(item.get('model', 'model'))}**: {_markdown_text(item.get('risk_level', 'unknown'))}{confidence_label}"
            )
            explanation = str(item.get("explanation") or "").strip()
            if explanation:
                lines.append(f"  - {_markdown_text(explanation, multiline=True)}")
    if heuristic_findings:
        lines.append("\n## Technical Reasons")
        for item in heuristic_findings:
            lines.append(
                f"- **{_markdown_text(item.get('type', 'signal'))}** ({_markdown_text(item.get('severity', 'medium'))}): {_markdown_text(item.get('detail', ''))}"
            )
    if evidence_buckets:
        lines.append("\n## Where The Risk Comes From")
        for item in evidence_buckets:
            lines.append(
                f"- **{_markdown_text(item.get('key', 'bucket'))}**: score {item.get('score', 0)} with {item.get('finding_count', 0)} finding(s)"
            )
            if item.get("summary"):
                lines.append(f"  - {_markdown_text(item.get('summary'), multiline=True)}")
    if url_evidence:
        lines.append("\n## Link Details")
        for item in url_evidence:
            lines.append(
                f"- **{_markdown_text(item.get('domain', ''))}** -> registered domain `{_markdown_text(item.get('registrable_domain', ''))}` with TLD `{_markdown_text(item.get('tld', ''))}`"
            )
    if url_live_inspection:
        lines.append("\n## Destination Check")
        for item in url_live_inspection:
            lines.append(f"- **{_markdown_text(item.get('normalized_url', ''))}**")
            if item.get("blocked_reason"):
                lines.append(f"  - blocked: {_markdown_text(item.get('blocked_reason'))}")
                continue
            if item.get("error") and not item.get("inspection_succeeded"):
                lines.append(f"  - error: {_markdown_text(item.get('error'))}")
                continue
            lines.append(f"  - final: `{_markdown_text(item.get('final_url') or item.get('normalized_url'))}`")
            lines.append(f"  - redirects: {len(item.get('redirect_chain') or [])}")
            if item.get("status_code") is not None:
                lines.append(f"  - status: {item.get('status_code')}")
            if item.get("page_title"):
                lines.append(f"  - title: {_markdown_text(item.get('page_title'))}")
    if ocr_metadata:
        lines.append("\n## Screenshot OCR")
        if ocr_metadata.get("ocr_confidence") is not None:
            lines.append(f"- confidence: {round(float(ocr_metadata['ocr_confidence']) * 100)}%")
        if ocr_metadata.get("layout_summary"):
            lines.append(f"- layout: {_markdown_text(ocr_metadata.get('layout_summary'), multiline=True)}")
        if ocr_metadata.get("ocr_override_used"):
            lines.append("- manual override: yes")
        warnings = ocr_metadata.get("ocr_warnings") or []
        if warnings:
            lines.append("- warnings:")
            for item in warnings:
                lines.append(f"  - {_markdown_text(item)}")
        visual_signals = ocr_metadata.get("visual_signals") or []
        if visual_signals:
            lines.append("- visual signals:")
            for item in visual_signals:
                lines.append(
                    f"  - **{_markdown_text(item.get('type', 'signal'))}** ({_markdown_text(item.get('severity', 'medium'))}): {_markdown_text(item.get('detail', ''))}"
                )
        qr_payloads = ocr_metadata.get("qr_payloads") or []
        if qr_payloads:
            lines.append("\n## Detected QR Codes")
            for item in qr_payloads:
                lines.append(f"- `{_markdown_text(item)}`")
    if document_metadata:
        lines.append("\n## Document X-Ray")
        lines.append(f"- **File:** {_markdown_text(document_metadata.get('file_name', 'uploaded-document'))}")
        lines.append(f"- **Type:** {_markdown_text(document_metadata.get('file_type', 'document')).upper()}")
        if document_metadata.get("parser"):
            lines.append(f"- **Parser:** {_markdown_text(document_metadata.get('parser'))}")
        lines.append(f"- **Inspectable:** {'yes' if document_metadata.get('inspectable', True) else 'limited'}")
        if document_metadata.get("protected"):
            lines.append("- **Protected or encrypted:** yes")
        if document_metadata.get("macro_enabled"):
            lines.append("- **Macro-enabled:** yes")
        if document_metadata.get("image_based"):
            lines.append("- **Image-based:** yes")
        if document_metadata.get("ocr_fallback_used"):
            line = f"- **OCR fallback:** yes ({document_metadata.get('ocr_pages_analyzed', 0)} page(s) checked"
            if document_metadata.get("ocr_page_limit"):
                line += f", limit {document_metadata.get('ocr_page_limit')}"
            line += ")"
            lines.append(line)
        if document_metadata.get("page_count") is not None:
            lines.append(f"- **Pages:** {document_metadata.get('page_count')}")
        if document_metadata.get("section_count") is not None:
            lines.append(f"- **Sections:** {document_metadata.get('section_count')}")
        if document_metadata.get("image_count") is not None:
            lines.append(f"- **Embedded images:** {document_metadata.get('image_count')}")
        if document_metadata.get("text_preview"):
            lines.append(f"- **Preview:** {_markdown_text(document_metadata.get('text_preview'), multiline=True)}")
        limitations = document_metadata.get("limitations") or []
        if limitations:
            lines.append("\n### Inspection Limitations")
            for item in limitations:
                lines.append(f"- {_markdown_text(item)}")
        link_pairs = document_metadata.get("link_pairs") or []
        if link_pairs:
            lines.append("\n### Embedded Links")
            for item in link_pairs:
                display_text = item.get("display_text") or "link"
                target_url = item.get("target_url") or "unknown destination"
                lines.append(f"- **{_markdown_text(display_text)}** -> `{_markdown_text(target_url)}`")
        qr_payloads = document_metadata.get("qr_payloads") or []
        if qr_payloads:
            lines.append("\n### Detected Document QR Codes")
            for item in qr_payloads:
                lines.append(f"- `{_markdown_text(item)}`")
    if voice_metadata:
        lines.append("\n## Call Guard")
        lines.append(f"- **Session ID:** `{_markdown_text(voice_metadata.get('session_id', 'voice-session'))}`")
        if voice_metadata.get("analysis_state"):
            lines.append(f"- **State:** {_markdown_text(voice_metadata.get('analysis_state'))}")
        if voice_metadata.get("elapsed_seconds") is not None:
            lines.append(f"- **Elapsed:** {voice_metadata.get('elapsed_seconds')}s")
        if voice_metadata.get("transcript_word_count") is not None:
            lines.append(f"- **Transcript Words:** {voice_metadata.get('transcript_word_count')}")
        warnings = voice_metadata.get("live_warnings") or []
        if warnings:
            lines.append("- **Live Warnings:**")
            for item in warnings:
                lines.append(f"  - {_markdown_text(item)}")
        questions = voice_metadata.get("challenge_questions") or []
        if questions:
            lines.append("- **Challenge Questions:**")
            for item in questions:
                lines.append(f"  - {_markdown_text(item)}")
        voice_signals = voice_metadata.get("voice_signals") or []
        if voice_signals:
            lines.append("- **Voice-Pattern Signals:**")
            for item in voice_signals:
                lines.append(
                    f"  - **{_markdown_text(item.get('type', 'voice_signal'))}** ({_markdown_text(item.get('severity', 'low'))}): {_markdown_text(item.get('detail', ''))}"
                )
        segments = voice_metadata.get("transcript_segments") or []
        if segments:
            lines.append("- **Transcript Segments:**")
            for item in segments[-8:]:
                lines.append(f"  - {_markdown_text(item.get('text', ''))}")
    if payload.get("redacted_input"):
        redaction_count = payload.get("metadata", {}).get("redaction_count", 0)
        lines.append(f"\n> {translations['privacy_mode']}: {redaction_count} item(s) redacted before analysis")
    lines.append(f"\n---\n{translations['generated_by']}")
    return "\n".join(lines)
